### ISSUE TITLE
Create a branch of V01-07-00

### ISSUE THREAD

**Issue by jpata** [cms-data/RecoBTag-Combined#39]
Hi, can you please create a branch for the tag V01-07-00 (https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/data/cmsswdata.txt#L9 for 10_6_X) so we can backport the data PR https://github.com/cms-data/RecoBTag-Combined/pull/37 for the PR https://github.com/cms-sw/cmssw/pull/32647.

🤯

**Comment by smuzaffar** [comment]
https://github.com/cms-data/RecoBTag-Combined/tree/CMSSW_10_6_X branch (based on V00-07-00) is now available
