### ISSUE TITLE
Tagging and creating cmsdist data PR for non-master branches

### ISSUE THREAD

**Issue by smuzaffar** [cms-data/RecoBTag-Combined#41]
@mrodozov , I think for non-master/main branch you can use `git log ...` command to find the latest tag e.g
```
> git clone git@github.com:cms-data/RecoBTag-Combined
> cd RecoBTag-Combined/
> git checkout CMSSW_10_6_X
> git log --pretty='"%s", "%d"' CMSSW_10_6_X | grep origin/CMSSW_10_6_X
"Merge pull request #40 from leonardogiannini/CMSSW_10_6_X", " (tag: V01-07-01, origin/CMSSW_10_6_X, CMSSW_10_6_X)"
> git checkout CMSSW_10_2_X
> git log --pretty='"%s", "%d"' CMSSW_10_2_X | grep origin/CMSSW_10_2_X
"Merge pull request #29 from cms-data/010103plus", " (HEAD, tag: V01-03-01, tag: V01-01-03-01, origin/CMSSW_10_2_X, CMSSW_10_2_X)"
```

then simple sed/grep should be able to get you the tag on that branch.

**Comment by smuzaffar** [comment]
OR you can use https://api.github.com/repos/cms-data/RecoBTag-Combined/branches to find the branches and their sha and then use https://api.github.com/repos/cms-data/RecoBTag-Combined/tags to see which tag assiigned to this sha

**Comment by mrodozov** [comment]
second one is better it excludes parsing strings (less possible errors)
